### ISSUE TITLE
`image:push` runs the build multiple times when used with an `env` resource

### ISSUE THREAD

**Issue by cescoferraro** [dnephin/dobi#74] opened 2017-01-17 16:58 UTC
```
env=vars:
    variables:
      - FRONTEND_VERSION=0.1.7
      - API_VERSION=0.1.17

job=api:
    description: "Builds API docker image"
    use: dev-image
    artifact: dist/spotify
    user: "{user.uid}"
    mounts: [source]
    interactive: true
    command:   bash -c "go build -o dist/spotify -ldflags \"-X main.VERSION=$API_VERSION\" src/api/*.go"
    depends: [vars]
    env:
      - "API_VERSION={env.API_VERSION}"
      - "GODEBUG=http2client=0"

image=api-image:
    image: cescoferraro/spotify
    tags: ["api-{env.API_VERSION}"]
    dockerfile: build/docker/Dockerfile.api
    depends: [vars, api]
    description: "Build the api-image"
```

### Build
```
cescoferraro@mint-pro: ~/code/go/src/github.com/cescoferraro/spotify on master [+!$]
$ dobi api-image
[env:set vars] Done
[image:build dev-image] cescoferraro/spotify is fresh
[env:set vars] Done
[job: api] bash -c "go build -o dist/spotify -ldflags \"-X main.VERSION=$API_VERSION\" src/api/*.go" -> dist/spotify Start
[job: api] bash -c "go build -o dist/spotify -ldflags \"-X main.VERSION=$API_VERSION\" src/api/*.go" -> dist/spotify Done
Step 1 : FROM golang
latest: Pulling from library/golang
Digest: sha256:5787421a0314390ca8da11b26885502b58837ebdffda0f557521790c13ddb55f
Status: Downloaded newer image for golang:latest
 ---> 6639f812dbc7
Step 2 : MAINTAINER Francesco Ferraro <francescoaferraro@gmail.com>
 ---> Running in fcfbc3a6a97c
 ---> 889dd4c3c51b
Removing intermediate container fcfbc3a6a97c
Step 3 : ADD www/ www
 ---> d76564cf30e4
Removing intermediate container 52a6c19a1574
Step 4 : ADD dist/spotify spotify
 ---> bf693f142553
Removing intermediate container 4d65fd8dd41e
Step 5 : ENV PORT 8080
 ---> Running in d8fda0735f3c
 ---> 7e6ddde0cb70
Removing intermediate container d8fda0735f3c
Step 6 : EXPOSE 8080
 ---> Running in 89a83d11b3f2
 ---> c949bc3da0b7
Removing intermediate container 89a83d11b3f2
Step 7 : ENTRYPOINT /spotify
 ---> Running in 8c99cc99d277
 ---> 16c0a85747ca
Removing intermediate container 8c99cc99d277
Successfully built 16c0a85747ca
[image:build api-image] cescoferraro/spotify Created


```
### Push
```
cescoferraro@mint-pro: ~/code/go/src/github.com/cescoferraro/spotify on master [+!$]
$ dobi api-image:push
[env:set vars] Done
Step 1 : FROM golang:1.7.4
 ---> 6639f812dbc7
Step 2 : RUN apt-get install -y curl
 ---> Using cache
 ---> cbb7f2130c36
Step 3 : RUN curl -sL https://deb.nodesource.com/setup_6.x -o nodesource_setup.sh
 ---> Using cache
 ---> c99cfa54bfb2
Step 4 : RUN bash nodesource_setup.sh
 ---> Using cache
 ---> 9e5fb9e5d712
Step 5 : RUN apt-get install -y nodejs
 ---> Using cache
 ---> beb37f2c6cb4
Step 6 : RUN apt-get install -y build-essential
 ---> Using cache
 ---> d7fa22c4dd89
Step 7 : RUN go get github.com/cespare/reflex &&         cp /go/bin/reflex /usr/bin/ &&         rm -rf /go/src/* /go/pkg/* /go/bin/*
 ---> Using cache
 ---> 937d6028e42e
Step 8 : ENV PS1 "# "
 ---> Using cache
 ---> b7f4d2ff45c1
Step 9 : ENV GOBIN /go/binw
 ---> Using cache
 ---> d59cce53944b
Step 10 : ADD package.json package.json
 ---> Using cache
 ---> 8b373f48ed53
Step 11 : ENV CGO_ENABLED 0
 ---> Using cache
 ---> 4ec6c4327572
Step 12 : WORKDIR /go/src/github.com/cescoferraro/spotify
 ---> Using cache
 ---> a418964be539
Successfully built a418964be539
[image:build dev-image] cescoferraro/spotify Created
[env:set vars] Done
[job: api] bash -c "go build -o dist/spotify -ldflags \"-X main.VERSION=$API_VERSION\" src/api/*.go" -> dist/spotify Start
[job: api] bash -c "go build -o dist/spotify -ldflags \"-X main.VERSION=$API_VERSION\" src/api/*.go" -> dist/spotify Done
Step 1 : FROM golang
 ---> 6639f812dbc7
Step 2 : MAINTAINER Francesco Ferraro <francescoaferraro@gmail.com>
 ---> Using cache
 ---> 889dd4c3c51b
Step 3 : ADD www/ www
 ---> Using cache
 ---> d76564cf30e4
Step 4 : ADD dist/spotify spotify
 ---> Using cache
 ---> bf693f142553
Step 5 : ENV PORT 8080
 ---> Using cache
 ---> 7e6ddde0cb70
Step 6 : EXPOSE 8080
 ---> Using cache
 ---> c949bc3da0b7
Step 7 : ENTRYPOINT /spotify
 ---> Using cache
 ---> 16c0a85747ca
Successfully built 16c0a85747ca
[image:build api-image] cescoferraro/spotify Created
[env:set vars] Done
Step 1 : FROM golang:1.7.4
 ---> 6639f812dbc7
Step 2 : RUN apt-get install -y curl
 ---> Using cache
 ---> cbb7f2130c36
Step 3 : RUN curl -sL https://deb.nodesource.com/setup_6.x -o nodesource_setup.sh
 ---> Using cache
 ---> c99cfa54bfb2
Step 4 : RUN bash nodesource_setup.sh
 ---> Using cache
 ---> 9e5fb9e5d712
Step 5 : RUN apt-get install -y nodejs
 ---> Using cache
 ---> beb37f2c6cb4
Step 6 : RUN apt-get install -y build-essential
 ---> Using cache
 ---> d7fa22c4dd89
Step 7 : RUN go get github.com/cespare/reflex &&         cp /go/bin/reflex /usr/bin/ &&         rm -rf /go/src/* /go/pkg/* /go/bin/*
 ---> Using cache
 ---> 937d6028e42e
Step 8 : ENV PS1 "# "
 ---> Using cache
 ---> b7f4d2ff45c1
Step 9 : ENV GOBIN /go/binw
 ---> Using cache
 ---> d59cce53944b
Step 10 : ADD package.json package.json
 ---> Using cache
 ---> 8b373f48ed53
Step 11 : ENV CGO_ENABLED 0
 ---> Using cache
 ---> 4ec6c4327572
Step 12 : WORKDIR /go/src/github.com/cescoferraro/spotify
 ---> Using cache
 ---> a418964be539
Successfully built a418964be539
[image:build dev-image] cescoferraro/spotify Created
[env:set vars] Done
[job: api] bash -c "go build -o dist/spotify -ldflags \"-X main.VERSION=$API_VERSION\" src/api/*.go" -> dist/spotify Start
[job: api] bash -c "go build -o dist/spotify -ldflags \"-X main.VERSION=$API_VERSION\" src/api/*.go" -> dist/spotify Done
[image:tag api-image] cescoferraro/spotify Tagged
[env:set vars] Done
Step 1 : FROM golang:1.7.4
 ---> 6639f812dbc7
Step 2 : RUN apt-get install -y curl
 ---> Using cache
 ---> cbb7f2130c36
Step 3 : RUN curl -sL https://deb.nodesource.com/setup_6.x -o nodesource_setup.sh
 ---> Using cache
 ---> c99cfa54bfb2
Step 4 : RUN bash nodesource_setup.sh
 ---> Using cache
 ---> 9e5fb9e5d712
Step 5 : RUN apt-get install -y nodejs
 ---> Using cache
 ---> beb37f2c6cb4
Step 6 : RUN apt-get install -y build-essential
 ---> Using cache
 ---> d7fa22c4dd89
Step 7 : RUN go get github.com/cespare/reflex &&         cp /go/bin/reflex /usr/bin/ &&         rm -rf /go/src/* /go/pkg/* /go/bin/*
 ---> Using cache
 ---> 937d6028e42e
Step 8 : ENV PS1 "# "
 ---> Using cache
 ---> b7f4d2ff45c1
Step 9 : ENV GOBIN /go/binw
 ---> Using cache
 ---> d59cce53944b
Step 10 : ADD package.json package.json
 ---> Using cache
 ---> 8b373f48ed53
Step 11 : ENV CGO_ENABLED 0
 ---> Using cache
 ---> 4ec6c4327572
Step 12 : WORKDIR /go/src/github.com/cescoferraro/spotify
 ---> Using cache
 ---> a418964be539
Successfully built a418964be539
[image:build dev-image] cescoferraro/spotify Created
[env:set vars] Done
[job: api] bash -c "go build -o dist/spotify -ldflags \"-X main.VERSION=$API_VERSION\" src/api/*.go" -> dist/spotify Start
[job: api] bash -c "go build -o dist/spotify -ldflags \"-X main.VERSION=$API_VERSION\" src/api/*.go" -> dist/spotify Done
The push refers to a repository [docker.io/cescoferraro/spotify]
58b328818efb: Pushed 
540ea697ec3f: Pushed 
8b77aafa7afb: Mounted from library/golang 
988a4cf7bfad: Mounted from library/golang 
e6769ace411a: Mounted from library/golang 
779900daf86c: Mounted from library/golang 
53c779688d06: Mounted from library/golang 
60a0858edcd5: Mounted from library/golang 
b6ca02dfe5e6: Mounted from library/golang 
api-0.1.16: digest: sha256:066b1f33224cda57b2a645a8751ef32b80b0806e909c547397a3ca60ee54aea1 size: 2214
[image:push api-image] cescoferraro/spotify Pushed

```

**Comment by dnephin** [comment] 2017-01-17 17:02
What's the bug? That it has to rebuild the images?

**Comment by cescoferraro** [comment] 2017-01-17 17:23
@dnephin it runs the api job 3 times before actually pushing

**Comment by dnephin** [comment] 2017-01-17 17:27
`:push` depends on `:tag`, which depends on `:build`, which is ok, but once we added variables it's hard to figure out if the task needs to be forced or not.

The problem is that because of the variables it thinks it has to rebuild each time. I think the logic [here](https://github.com/dnephin/dobi/blob/master/tasks/tasks.go#L82) needs to be a lot more complex.

**Comment by cescoferraro** [comment] 2018-02-17 19:54
this is burning my free CircleCI minutes
do you mean https://github.com/dnephin/dobi/blob/master/tasks/tasks.go#L78 ?
@dnephin why would an env resource invalidates the tasksConfigs cache?

**Comment by dnephin** [comment] 2018-02-17 20:02
Ya, that's the one. It's because env can change the output of a task, so you can't reliably cache it unless you include env as part of the cache key. So the fix would be to have the cache depend on env, not just the task having run.

**Comment by Fuco1** [comment] 2018-07-20 15:52
This is not necessarily related to pushing.  I have three jobs which use an image I've built previously which depends on env.  Each of the jobs triggers the entire chain of building the image again.

The relevant part of the config looks something like this

```yaml
# Build the dev dependencies image
env=deps-dev-settings:
  files: [build/lockfile_hash]
  variables:
    - NPM_TOKEN={env.NPM_TOKEN}

image=deps-dev:
  image: dependencies
  pull: always
  tags: ["{env.LOCKFILE_HASH}-dev"]
  dockerfile: Dockerfile.deps.dev
  depends:
    - deps-dev-settings
  args:
    NPM_TOKEN: "{env.NPM_TOKEN}"

# Build the dev image
image=dev:
  image: "{env.LOCKFILE_HASH}-dev"
  dockerfile: Dockerfile.dev
  depends: [deps-dev]
  tags: [dev]

# Run the tests
job=eslint:
  use: dev
  command: "yarn run eslint lib test"

job=eclint:
  use: dev
  command: "yarn run eclint check lib test"

job=test:
  use: dev
  command: "yarn test"

alias=tests:
  tasks:
    - eslint
    - eclint
    - test
```

Running `dobi tests` triggers the build of `dev` which in turns triggers `deps-dev` and because that depends on the env it is rebuilt every time (at least I think this is what happens).

**Comment by dnephin** [comment] 2018-07-22 21:39
I think #147 may be a fix for this issue

**Comment by Fuco1** [comment] 2018-07-23 09:18
@dnephin If there are some instructions on how to build the branch I'll be happy to try this patch out.  But I have no idea about go and its ecosystem.

**Closed** 2018-07-28 20:16 UTC
Labels: area/task, kind/bug
