### ISSUE TITLE
Pulling images doesn't seem to work

### ISSUE THREAD

**Issue by bfirsh** [dnephin/dobi#24] opened 2016-10-03 13:44 UTC
dobi.yaml:

```
...

image=go-swagger:
    image: "quay.io/goswagger/swagger:0.6.0"
    pull: once

job=go-swagger-validate:
    use: go-swagger
    command: "validate /code/swagger.yaml"
    ...
```

```
$ dobi go-swagger-validate
[image:build go-swagger] quay.io/goswagger/swagger:0.6.0 Building
[ERROR] Failed to execute task "go-swagger:build": missing remote repository e.g. 'github.com/user/repo'
```

There's no example of how to do this, so I'm guessing this is correct. Either I've got it wrong and an example is needed, or it's actually broken.

**Comment by dnephin** [comment] 2016-10-03 14:02
hmm, that's a weird error. I think that I didn't fully implement auth for non-hub registries, not sure if that's the issue. I'll look into it further.

**Comment by dnephin** [comment] 2016-10-03 14:16
Ok, so here's what I've found:

* with dobi 0.5 I can reproduce the error you're seeing
* that error was fixed in [dobi 0.6](https://github.com/dnephin/dobi/releases/tag/v0.6) (see the release notes about pull) and the error is now " unauthorized: authentication required", which is what I expected
* `image` should only ever be the image name without a tag. I should add a better error if an image tag is detected in the field. The config should be:

  ```yaml
  image=go-swagger:
    image: "quay.io/goswagger/swagger"
    tags: [0.6.0]
    pull: once
  ```

* the error is probably caused by this missing code: https://github.com/dnephin/dobi/blob/master/tasks/image/inspect.go#L33-L36 It sends the wrong auth for that registry.

I'll submit a fix for both of those issues.

**Comment by bfirsh** [comment] 2016-10-03 14:27
Thanks. Upgraded to 0.6, but it seems to require auth for an image which doesn't (I think?):

```
ben@computer ~/p/docker-api-reference [master]
± % dobi go-swagger-validate                                                        !97
[WARN] [image:pull go-swagger] quay.io/goswagger/swagger Failed to get image record: stat /Users/ben/p/docker-api-reference/.dobi/images/quay.io goswagger swagger:0.6.0: no such file or directory
[ERROR] Failed to execute task "go-swagger:pull": API error (401): Get https://quay.io/v2/goswagger/swagger/manifests/0.6.0: unauthorized: authentication required


ben@computer ~/p/docker-api-reference [master]
± % docker pull quay.io/goswagger/swagger:0.6.0                                     !98
0.6.0: Pulling from goswagger/swagger
e110a4a17941: Already exists
3f334f20cdfb: Already exists
6effbd395226: Already exists
Digest: sha256:3d1f8e34a70a528a421a921a0c3bc9ada5bb16aad4404d70dd40d8bee1702573
Status: Image is up to date for quay.io/goswagger/swagger:0.6.0
```

**Comment by dnephin** [comment] 2016-10-03 14:30
Ya, there is still a bug with the auth.

**Closed** 2016-10-03 19:21 UTC
Labels: area/task, kind/bug
